name: finance_quote
description: A multi-platform API to retrieve quote information and prices for stocks (e.g. Amazon, Google), commodities (e.g. Gold, Oil) and crypto-currencies (e.g. Bitcoin, Ethereum).
version: 0.1.2
author: "Ismael Jiménez <ijimenezm@hotmail.es>"
homepage: https://github.com/ismaelJimenez/finance_quote

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  html: ^0.15.0
  http: ^0.13.0
  intl: ^0.17.0
  logger: ^1.0.0-nullsafety.0
  meta: ^1.3.0

dev_dependencies:
  mockito: ^5.0.0
  pedantic: ^1.11.0
  test: ^1.16.5
